import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve as resolvePath } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const pdfOutPath = resolvePath(here, '..', 'src', 'assets', 'fixtures', 'demo.pdf');
const b64OutPath = resolvePath(
  here,
  '..',
  'src',
  'app',
  'core',
  'services',
  'demo-pdf.b64.ts',
);

async function buildFixturePdf(): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595, 842]);
  const font = await doc.embedFont(StandardFonts.Helvetica);

  page.drawText('Engclass Demo', {
    x: 50,
    y: 780,
    size: 24,
    font,
    color: rgb(0.1, 0.1, 0.1),
  });

  page.drawText('Haz clic en cualquier punto de la pagina para anadir una respuesta.', {
    x: 50,
    y: 740,
    size: 12,
    font,
    color: rgb(0.25, 0.25, 0.25),
  });

  page.drawRectangle({
    x: 50,
    y: 200,
    width: 495,
    height: 500,
    borderColor: rgb(0.6, 0.6, 0.6),
    borderWidth: 1,
  });

  return doc.save();
}

async function main(): Promise<void> {
  const bytes = await buildFixturePdf();
  await mkdir(dirname(pdfOutPath), { recursive: true });
  await mkdir(dirname(b64OutPath), { recursive: true });
  await writeFile(pdfOutPath, bytes);

  const base64 = Buffer.from(bytes).toString('base64');
  const banner =
    '// AUTO-GENERATED by apps/web/scripts/build-fixture.ts - do not edit by hand.\n' +
    "// Regenerate with `pnpm --filter @engclass/web fixtures:build`.\n\n";
  const contents =
    banner +
    `export const DEMO_PDF_BYTES = ${bytes.length} as const;\n` +
    `export const DEMO_PDF_BASE64 = ${JSON.stringify(base64)};\n`;
  await writeFile(b64OutPath, contents, 'utf8');

  console.log(`wrote ${pdfOutPath} (${bytes.length} bytes)`);
  console.log(`wrote ${b64OutPath} (${base64.length} base64 chars)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});