import { config } from 'dotenv';
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(here, '..');
const envPath = join(projectRoot, '.env');
const fallbackPath = join(projectRoot, '.env.example');

const source = existsSync(envPath) ? envPath : fallbackPath;
config({ path: source });

const isProd = (process.env.NODE_ENV ?? '').trim() === 'production';
const apiBaseUrl = process.env.API_BASE_URL ?? 'http://localhost:3000/api/v1';
const useMockApiRaw = process.env.USE_MOCK_API ?? (isProd ? 'false' : 'true');
const useMockApi = ['1', 'true', 'yes', 'on'].includes(useMockApiRaw.toLowerCase());
const cookieDomain = process.env.COOKIE_DOMAIN ?? (isProd ? '' : 'localhost');

const outPath = join(projectRoot, 'src', 'environments', 'environment.local.ts');
const content =
  '// AUTO-GENERATED by scripts/sync-env.ts - do not edit.\n' +
  `export const environment = {\n` +
  `  production: ${isProd},\n` +
  `  apiBaseUrl: ${JSON.stringify(apiBaseUrl)},\n` +
  `  useMockApi: ${useMockApi},\n` +
  `  cookieDomain: ${JSON.stringify(cookieDomain)},\n` +
  `};\n`;

writeFileSync(outPath, content, 'utf8');
console.log(
  `[sync-env] source=${source} apiBaseUrl=${apiBaseUrl} useMockApi=${useMockApi} production=${isProd}`,
);
