import { config } from 'dotenv';
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(here, '..');
const envPath = join(projectRoot, '.env');
const fallbackPath = join(projectRoot, '.env.example');

const source = existsSync(envPath) ? envPath : fallbackPath;
config({ path: source });

const apiBaseUrl = process.env.API_BASE_URL ?? 'http://localhost:3000/api/v1';
const production = (process.env.NODE_ENV ?? '').trim() === 'production';

const outPath = join(projectRoot, 'src', 'environments', 'environment.local.ts');
const content =
  '// AUTO-GENERATED by scripts/sync-env.ts - do not edit.\n' +
  `export const environment = {\n` +
  `  production: ${production},\n` +
  `  apiBaseUrl: ${JSON.stringify(apiBaseUrl)},\n` +
  `};\n`;

writeFileSync(outPath, content, 'utf8');
console.log(`[sync-env] source=${source} apiBaseUrl=${apiBaseUrl} production=${production}`);
